### ISSUE TITLE
configure fails on Debian 8 and Fedora 21

### ISSUE THREAD

**Issue by Xe** [Elemental-IRCd/elemental-ircd#103]
```
xena@fluttershy (linux) ~/code/elemental-ircd
➜  ./autogen.sh 2>&1 | gist -sp
http://git.io/vqAgX
xena@fluttershy (linux) ~/code/elemental-ircd
➜  ./configure 2>&1 | gist -sp               
http://git.io/vqAgd
```

I'm on git head, commit `cede6a074389cc4d0919f401d7750b128a304c72`.

**Comment by Xe** [comment]
And bisecting says https://github.com/Elemental-IRCd/elemental-ircd/commit/7d5a840e2c075e3ec3a093f7e5959fc6bddb48e1 is the first bad commit. Wat.

**Comment by ariscop** [comment]
Need autoconf-archive for AX_APPEND_COMPILE_FLAGS
