### ISSUE TITLE
Feature request: Adding the instruction to umode +g to tell users how to accept a PM

### ISSUE THREAD

**Issue by omnicons** [Elemental-IRCd/elemental-ircd#133]
While having the current statement and documentation available, it is available elsewhere to have the statement: 'Use /ACCEPT $user to allow' follow the initial message that a user is trying to message you, which would be simpler to have than having a user go through the help each time.

**Comment by Xe** [comment]
:+1:

**Comment by skyhighwings** [comment]
:+1:

**Comment by skyhighwings** [comment]
It looks to me like all that would need to be updated would be https://github.com/Elemental-IRCd/elemental-ircd/blob/master/src/messages.tab#L742 and then the arguments of https://github.com/Elemental-IRCd/elemental-ircd/blob/master/modules/core/m_message.c#L776-L779 and https://github.com/Elemental-IRCd/elemental-ircd/blob/master/modules/core/m_message.c#L790-L794

**Comment by Xe** [comment]
[in progress here](https://github.com/Elemental-IRCd/elemental-ircd/commits/fix/help/mode-g).
