### ISSUE TITLE
Windows build broken (Incorrect EISCONN check)

### ISSUE THREAD

**Issue by ariscop** [Elemental-IRCd/elemental-ircd#139]
See: https://github.com/Elemental-IRCd/elemental-ircd/blob/master/libratbox/src/commio.c#L457-L464

There's nothing actually wrong with this code, however mingw includes an errno.h that does not match the wsa errors actually returned by connect() on windows.

Need a mapping between windows errors and errno, or some other way to fix these checks (redefine error macros?).
Either way libratbox (as much as possible) must use and return unix-ish error macros, don't want windowsism back in the codebase

**Comment by dequis** [comment]
Evidently the only way to escape the hole you've dug is to keep digging. Makes sense.

**Comment by ariscop** [comment]
yeah but as much as possible the digging is restricted to libratbox/platform/windows.c, rest of the codebase will be kept blissfully unaware of the horrors it's been ported to

**Comment by ariscop** [comment]
So my original assumption was wrong, ratbox had a thing which was causing the WSA* errors to leak through, connect() has unixish returns already

There's some deeper problem breaking connect()

**Comment by ariscop** [comment]
Not going to go forward with the windows port anymore
