### ISSUE TITLE
MONITOR metabug

### ISSUE THREAD

**Issue by Xe** [Elemental-IRCd/elemental-ircd#150]
- [x] Monitor replies should always send a hostmask when available

**Comment by ariscop** [comment]
[ircv3.2](http://ircv3.net/specs/core/monitor-3.2.html) doesn't mention RPL_ENDOFMONLIST in response to MONITOR S, doc/monitor.txt mentions it but pr #151 removes that to match the v3.2 spec

**Comment by ariscop** [comment]
#151 SHOULD also remove the last instances of a hostmask being sent, needs to be checked. tests are updated to not expect it

**Comment by ariscop** [comment]
After much 'discussion' in #ircv3, it's been decided that the spec is wrong since it doesn't match the majority of implementation, and a hostmask should be sent

RPL_ENDOFMONLIST doesn't seem to be sent by any other implementation, so we won't lest it break MONITOR L

**Comment by ariscop** [comment]
Fixed by #157
