### ISSUE TITLE
Move module ISUPPORT lines into the modules themselves

### ISSUE THREAD

**Issue by Xe** [Elemental-IRCd/elemental-ircd#179]
This was a surprising thing to see.

- [x] `MONITOR` `modules/m_monitor.so`
- [x] `CPRIVMSG`/`CNOTICE` `modules/m_cmessage.so`
- [x] `SAFELIST`/`ELIST` `modules/m_list.so`
- [x] `ETRACE` `modules/m_trace.so`
- [x] `KNOCK` `modules/m_knock.so`
- [x] `WHOX` `modules/m_who.so`

**Comment by ariscop** [comment]
TARGMAX contains "MONITOR:", does that need to be updated as well?

**Comment by Xe** [comment]
i'm kinda afraid to touch that as I don't know what reads and relies on TARGMAX.
