### ISSUE TITLE
Fails to compile on FreeBSD

### ISSUE THREAD

**Issue by blindirc** [Elemental-IRCd/elemental-ircd#18]
Compiling with openssl throws out these errors: 

http://pastebin.com/sd7K9jwx

Running FreeBSD Version:  FreeBSD freebsd 10.0-RELEASE FreeBSD 10.0-RELEASE #0 r260789: Thu Jan 16 22:34:59 UTC 2014     root@snap.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

Only way to compile and run the IRCd is by doing ./configure --disable-openssl.

**Comment by Xe** [comment]
Is this still an issue?

**Comment by ariscop** [comment]
https://github.com/Elemental-IRCd/elemental-ircd/pull/86 may break or fix *bsd support, if you're still interested please test

**Comment by ariscop** [comment]
Fixed by https://github.com/Elemental-IRCd/elemental-ircd/pull/90
