### ISSUE TITLE
Add pkg-config to install requirements

### ISSUE THREAD

**Issue by demize** [Elemental-IRCd/elemental-ircd#197]
pkg-config is a requirement to install, however it is not mentioned in the README. `apt-get install pkg-config` installs it on Debian/Ubuntu, and I'm not sure what installs it with yum/dnf.

**Comment by Xe** [comment]
Ah, the `build-essential` package doesn't also include `pkg-config`?

**Comment by demize** [comment]
It does not. It's a fairly commonly installed package, so most people will have it; the only reason I noticed is because I was installing on a fresh Debian system.

**Comment by Xe** [comment]
Done.
