### ISSUE TITLE
feature request: support haproxy's proxy protocol

### ISSUE THREAD

**Issue by skyhighwings** [Elemental-IRCd/elemental-ircd#199]
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

This is basically `X-Forwarded-For` for TCP. It would be an interesting idea to see if this can be used for transparently multi-node servers which can arbitrarily scale up/down.

**Comment by Xe** [comment]
One major thing to keep in mind that any IRC daemons with something like this loaded would need to have an explicit whitelist of servers that it can accept those "promotable" connections from, maybe this should be implemented inside the `WEBIRC` module.

**Comment by skyhighwings** [comment]
Absolutely!

Honestly, something which would be super cool would be transparently shuffling users between servers behind a load balancer, so that scaling down is no problem.

**Comment by aji** [comment]
the actual challenge to this proposal is implementing a way for a new server to start handling the connection of an old server. as it turns out, this is very hard, and will definitely become the focus of implementing some kind of proxied IRC architecture
