### ISSUE TITLE
Remove the existing config parser, re-implement in TCL

### ISSUE THREAD

**Issue by Xe** [Elemental-IRCd/elemental-ircd#208]
The existing flex/bison config parser does work. However it is very painful to work on and somewhat confusing for newer users. It also leaks memory, which is kind of impressive for generated code like this.

I think it might be a better idea to re-implement the existing configuration parsing so that vanilla configuration files can be loaded as TCL code which is then sanity checked after all the data structures are created. This would allow for you to define an oper as having a connection class that doesn't exist yet, remote loading and parsing of configuration data, and open the door for later extension of Elemental using TCL.

**Comment by kaniini** [comment]
Scripting languages really shouldn't be used for configuration, it is a security nightmare.
