### ISSUE TITLE
Atheme module: Support cmode +u

### ISSUE THREAD

**Issue by Xe** [Elemental-IRCd/elemental-ircd#25]

**Comment by dequis** [comment]
+u being auditorium?

**Comment by Xe** [comment]
+u in this case is `MODE_HIDEBANS`, something a network evaluating elemental requested.

**Comment by ShaleCoders** [comment]
Any updates on this?

**Comment by Xe** [comment]
@ShaleCoders I'm sorry this took so long. Real life gets in the way.

**Comment by ShaleCoders** [comment]
@xe - fully understand. I'll give if a test later, thanks again
