### ISSUE TITLE
feature request: server notice logging channel

### ISSUE THREAD

**Issue by parkerbryan** [Elemental-IRCd/elemental-ircd#27]
A small but convenient feature of InspIRCd, allows logging of specified server notices into a central channel. Greatly helpful especially with client-side logging of that channel, and being able to discuss server notices with other administrators in-channel as they happen.

For enhanced security it could be stepped up a notch to refuse displaying server notices in it if the channel is not at least +O.

**Comment by Xe** [comment]
This is outside the goal of this project. Use extended services.
