### ISSUE TITLE
IRCd owner (+y) Support with Atheme Services

### ISSUE THREAD

**Issue by vinniemac** [Elemental-IRCd/elemental-ircd#3]
Just adding this one as I have use_owner enabled in the configuration and have done since the IRCd was started up.
This does not work on my network with Atheme Services 7.0.7
What is the integration with Atheme Services and this mode?

Atheme has an 'owner' module however upon loading it either manually or automatically it outputs the following:

MODLOAD: chanserv/owner
Module chanserv/owner requires owner support, refusing to load.

NOTE:
The IRCd also has admin support (+a) which is enabled on my network and this works with the 'Protect' Atheme module which loads successfully and allows this integration with no issues.

**Comment by Mihip** [comment]
nginx also fails.
