### ISSUE TITLE
Does vhost actually work?

### ISSUE THREAD

**Issue by YodaNetwork** [Elemental-IRCd/elemental-ircd#38]
So, I have 7 IPv4 addresses and about 6 IPv6 addresses on the system I'm running ElementalIRCd.
I'll be using 1.1.1._num_ just for example's sake to demonstrate what I'm trying to do.

I have the following in my config:

        vhost = "1.1.1.1";
        vhost6 = "2001:some:thin:g";

It's a simple issue really, from my understanding I _should_ only be able to connect to elemental via 1.1.1.1, but it appears not. I can connect from 1.1.1.2, 1.1.1.3, infact any IPv4 on the system.

The second I add another IPv4.. the second elemental binds to it.

Same for IPv6. Apologies if I didn't explain it clear enough.. I'm crap at doing stuff like this

Any insight into why this is happening?
(To note, all IPv4 are on `eth0`. (eth0:0, eth0:1 etc))

**Comment by Xe** [comment]
I have never seen an error like this before and previously didn't know about the `eth0:0` syntax. Is that for vlans?

I will look into this and patch things where appropriate. Are you sure you're not also listening on `0.0.0.0` somewhere?

**Comment by farcaller** [comment]
Any chance you can post `netstat -tnlp` output for relevant ports?

**Comment by YodaNetwork** [comment]
@farcaller Is this what you want?

tom@omega ~# netstat -tnlp | grep 6667
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:6667            0.0.0.0:*               LISTEN      -
tcp6       0      0 :::6667                 :::*                    LISTEN      -

**Comment by Xe** [comment]
Can you `sudo !!`?

**Comment by YodaNetwork** [comment]
@Xe Yes but it just repeats the last command ?

**Comment by AppleDash** [comment]
@YodaNetwork Yes, that would be the point. @Xe wants you to run `netstat -tnlp | grep 6667` as root.

**Comment by madyoda** [comment]
@AppleDash @Xe apologies, had never seen that command before.

tom@omega ~ # sudo netstat -tnlp | grep 6667
[sudo] password for tom:
tcp        0      0 0.0.0.0:6667            0.0.0.0:*               LISTEN      8463/ircd
tcp6       0      0 :::6667                 :::*                    LISTEN      8463/ircd
tom@omega ~ #

**Comment by madyoda** [comment]
Ah, crap.. Wrong account heh.

**Comment by Xe** [comment]
```
tcp 0 0 0.0.0.0:6667 0.0.0.0:* LISTEN 8463/ircd
tcp6 0 0 :::6667 :::* LISTEN 8463/ircd
```

Please post the relevant interface IP addresses and the server config with server link and operator blocks stripped? If you don't feel comfortable with posting it publicly please email me it (email listed on my github page).

**Comment by YodaNetwork** [comment]
@Xe Apologies for delay, was sleep.

Sent.

**Comment by Xe** [comment]
Try moving the `serverinfo::vhost` entry to a `listen::host` entry? https://github.com/Elemental-IRCd/elemental-ircd/blob/master/doc/reference.conf#L305

I am going to make another ticket about this referencing this one to point out this obvious confusing assertion error.

Thanks for finding this!

**Comment by YodaNetwork** [comment]
Fixed. Thank you @Xe!
How to fix:

 listen {
        defer_accept = yes;
        host = "1.1.1.1";
        port = 6665 .. 6669;
        sslport = 5555, 6697, 9999;

        host = "2001:some:thin:g";
        port = 6665 .. 6669;
        sslport = 5555, 6697, 9999;
};

etc etc..
