### ISSUE TITLE
Use qaohv?

### ISSUE THREAD

**Issue by Xe** [Elemental-IRCd/elemental-ircd#41]
Some compatibility issues with various IRC clients have come up and the idea of ditching the `yaohv ~!@%+` system that Elemental uses in favor of the unreal-style `qaohv ~&@%+` has been mentioned in a few places. As this change would be a *significant* breaking change with current releases of Elemental-IRCd, a new major release must be made to better facilitate upgrade paths. Additionally none of the `qaohv` work should be done in `master`.

This issue will be a metabug for discussion of how this will be implemented and the overall migration strategies that need to be developed to help networks running the "pre-`qahov`" elemental to the `qahov` elemental as well as submitting the correct patches to projects that build on Elemental-IRCd.

I suggest the following with regards to migrating Elemental-IRCd itself:

 - Add a required `QAOHV` server capability to the list of capabilities in the daemon link protocol, and have it reject any server link without this.
 - Replace references to `+y` with a `+q` or possibly a compiler macro.

As far as services go:
 - Notify the development team of the services package of the changes we are making and what changes they may need to make to their software to support this change
 - Submit a well-tested patch mending these issues

Anyone have any thoughts on this?

**Comment by Xe** [comment]
I am thinking that channel mode `+Q` would be used for quiets and `CMODE_DISFORWARD` would be changed to `+y` or removed altogether.

**Comment by Xe** [comment]
I am doing development on this in the [`qaohv`](https://github.com/Elemental-IRCd/elemental-ircd/tree/qaohv) branch.

**Comment by Xe** [comment]
`!janus.shadownet.int *** Notice -- ERROR :from rarity.shadownet.int -- Closing Link: 127.0.0.1 (Missing required CAPAB [QAOHV])`

**Comment by Xe** [comment]
Channel mode `+y` is now quiet and `+q` is now owner. This seemed like the path of least resistance.

**Comment by MrBenC** [comment]
What IRC client compatibility issues are you referring to?  And what will you do about local channels?

The ```qaohv ~&@%+``` system may also mean dropping support for local server channels or changing the prefix of local channels (breaking RFC1459 compliance).

As far as I know, Unreal and InspIRCd have never supported local channels, and I don't get the impression demand for them are high, so there might be something to be said for just dropping local channel support.

Ben

**Comment by Xe** [comment]
Not really. Elemental doesn't support messaging anything other than `@#channel` and `+#channel`.

As far as IRC clients, take your pick at random android/iphone ones, mibbit and Quassel.

**Comment by Xe** [comment]
This is not a goal for elemental-ircd.
