### ISSUE TITLE
Remove arc4random

### ISSUE THREAD

**Issue by Xe** [Elemental-IRCd/elemental-ircd#63]
https://github.com/Elemental-IRCd/elemental-ircd/blob/master/libratbox/src/arc4random.c

GPL Violation

**Comment by dequis** [comment]
Looks compatible to me

>Modification and redistribution in source and binary forms is
>permitted provided that due credit is given to the author and the
>OpenBSD project by leaving this copyright notice intact.

Only requirement is keeping the copyright notice, which is common to all permissive licenses compatible with GPL.

**Comment by dequis** [comment]
Actually, nevermind, nuke it. Even if it's gpl compatible, the whole file is a terrible idea. It reads from /dev/urandom and does dumb stuff to attempt to improve its randomness.

**Comment by Xe** [comment]
:boom:

**Comment by kaniini** [comment]
`arc4random()` is not used for cryptographically-secure things in libratbox.  However there is another PRNG interface which is arguably better, however you still need `arc4random` for the case where you build without TLS support.  Or are you making TLS a hard requirement?

**Comment by Xe** [comment]
See #57.
