### ISSUE TITLE
extended-join fails for fakequit users (on other servers?)

### ISSUE THREAD

**Issue by ariscop** [Elemental-IRCd/elemental-ircd#67]
:andrew!andrew@lou560-606-112-65.lns96.mel2.internode.on.net ACCOUNT :Phase4
    :andrew!andrew@lou560-606-112-65.lns96.mel2.internode.on.net QUIT :Changing host
    :andrew!andrew@phaselab JOIN :#BERRYPUNCH

Capabilities acknowledged on my client: account-notify extended-join multi-prefix sasl
the remote client (andrew) was on a different server

**Comment by Xe** [comment]
Fixed with #71
