### ISSUE TITLE
JOIN message is not compliant with ircv3.1 spec

### ISSUE THREAD

**Issue by rika314** [Elemental-IRCd/elemental-ircd#70]
I am getting ```:rika!~ping@user/rika JOIN #elemental-ircd rika 1433451721 :Serviteur de feu``` as JOIN message when extended-join capability is negotiated, however, [spec](http://ircv3.net/specs/extensions/extended-join-3.1.html) mandates that JOIN message should be in format of ```:nick!user@host JOIN #channelname accountname :Real Name```.  I guess that additional timestamp is transferred in order to decide which side should win after netsplit has happened and resolved, however doesn't confirm to spec, so, if someone could look on that and check if this timestamp could be removed from JOIN message, I would be very grateful. Thanks in advance.

**Comment by ariscop** [comment]
https://github.com/Elemental-IRCd/elemental-ircd/pull/71

**Comment by Xe** [comment]
fixed
