### ISSUE TITLE
Replace logging subsystem with stdout/syslog()

### ISSUE THREAD

**Issue by Xe** [Elemental-IRCd/elemental-ircd#95]
Things like systemd just listen for standard out or `syslog()` calls. If people really care about this ircd running, chances are they are going to be running it in something like systemd, or another bit of software that captures logging output.

The logging subsystem should be replaced with calls to `printf()` or `syslog()`. This will make log management much easier.

**Comment by ariscop** [comment]
I would like to see journald support as well, which can handle metadata syslog can't (line number, git ref, etc)

**Comment by Xe** [comment]
:+1: I'd like to see that too. A lot of the logging code in there is a nightmare.
